"""initial: users, clips, segments, audios

Revision ID: 2585d07e64db
Revises: 
Create Date: 2026-06-20 11:06:59.629574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2585d07e64db'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('handle', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('niche', sa.String(length=255), nullable=True),
    sa.Column('edge_pref', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('r2_key', sa.String(length=1024), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('bpm', sa.Float(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('beat_map', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('has_core_beat_drop', sa.Boolean(), nullable=False),
    sa.Column('beat_drop_ts', sa.Float(), nullable=True),
    sa.Column('structure', sa.String(length=32), nullable=True),
    sa.Column('thematic_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('energy_arc', sa.String(length=64), nullable=True),
    sa.Column('ig_audio_url', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audios_user_id'), 'audios', ['user_id'], unique=False)
    op.create_table('clips',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('r2_key', sa.String(length=1024), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('bitrate', sa.Integer(), nullable=True),
    sa.Column('twelvelabs_video_id', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('setting', sa.String(length=255), nullable=True),
    sa.Column('lighting_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('vibe_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('time_of_day', sa.String(length=64), nullable=True),
    sa.Column('color_temp_k', sa.Float(), nullable=True),
    sa.Column('avg_luminance', sa.Float(), nullable=True),
    sa.Column('dominant_palette', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('camera_movement', sa.String(length=64), nullable=True),
    sa.Column('has_speech', sa.Boolean(), nullable=True),
    sa.Column('has_music', sa.Boolean(), nullable=True),
    sa.Column('quality_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('embedding', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clips_status'), 'clips', ['status'], unique=False)
    op.create_index(op.f('ix_clips_user_id'), 'clips', ['user_id'], unique=False)
    op.create_table('segments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clip_id', sa.UUID(), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('start_ts', sa.Float(), nullable=False),
    sa.Column('end_ts', sa.Float(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('motion_intensity', sa.Float(), nullable=True),
    sa.Column('energy', sa.Float(), nullable=True),
    sa.Column('shot_scale', sa.String(length=64), nullable=True),
    sa.Column('lighting', sa.String(length=128), nullable=True),
    sa.Column('luminance', sa.Float(), nullable=True),
    sa.Column('color_temp_k', sa.Float(), nullable=True),
    sa.Column('subject_bbox', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('usability_score', sa.Float(), nullable=True),
    sa.Column('is_hero', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['clip_id'], ['clips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_segments_clip_id'), 'segments', ['clip_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_segments_clip_id'), table_name='segments')
    op.drop_table('segments')
    op.drop_index(op.f('ix_clips_user_id'), table_name='clips')
    op.drop_index(op.f('ix_clips_status'), table_name='clips')
    op.drop_table('clips')
    op.drop_index(op.f('ix_audios_user_id'), table_name='audios')
    op.drop_table('audios')
    op.drop_table('users')
    # ### end Alembic commands ###
